keywords({
  'default' => "Mastodon,tooot,social,decentralized,长毛象,社交,去中心"
})
privacy_url({
  'default' => "https://tooot.app/privacy-policy"
})
support_url({
  'default' => "https://tooot.app"
})
copyright("#{Time.now.year} ©️ xmflsct")
primary_category("SOCIAL_NETWORKING")

automatic_release(false)
force(true)
precheck_include_in_app_purchases(false)
submit_for_review(true)
overwrite_screenshots(true)

submission_information({
  add_id_info_limits_tracking: true,
  add_id_info_serves_ads: false,
  add_id_info_tracks_action: false,
  add_id_info_tracks_install: false,
  add_id_info_uses_idfa: true
})
